apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  # - ReadWriteMany
  # - ReadOnlyMany
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4

## kubectl create -f pv-definition.yaml
## kubectl get pv or kubectl get persistentvolume