apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

### kubectl create -f pvc-definition.yaml
### kubectl get persistentvolumeclaim or kubectl get pvc


##when the claim is created, it will try to find a matching PV based on the storage and access mode defined in the claim

## To delete a PVC
## kubectl delete pvc myclaim
#### what happens to the PV when the claim is deleted - it depends on the reclaim policy defined in the PV

# persistentVolumeReclaimPolicy - Retain, Recycle, Delete
# Retain - manual intervention is needed to delete the PV