apiVersion: apps/v1
kind: Deployment #just the kind changes rest of the yml stays the same wrt replicaset-definition.yml file
metadata:
  name: myapp-rc
  labels:
    app: demo-app
    type: front-end
  
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: demo-pod-app
        type: front-end
    spec:
      containers:
        - name: redis-image
          image: redis
  replicas: 3
  selector:
    matchLabels:
      type: front-end


# kubect create -f deployment-definition.yml
# kubectl get deployments
# kubectl get replicaset
# kubectl get pods
# kubectl get all