apiVersion: v1
kind: Config

current-context: dev-user@google


clusters:
- name: my-kube-playground
- name: development
- name: production
- name: google

contexts:
- name: my-kube-admin@my-kube-playground
- name: dev-user@google
- name: prod-user@production

users:
- name: my-kube-admin
- name: dev-user
- name: admin
- name: prod-user


### kubectl config view  /// to view the config file
### kubectl config view --kubeconfig=my-custom-config

## how to change the current context
### kubectl config use-context prod-user@production  /// to change the context to production

