apiVersion: v1
kind: Pod
metadata:
    name: simple-webapp
    labels:
    app: simple-webapp
spec:
    containers:
    - name: web-app
      image: web-app
      ports:
        - containerPort: 8080
    initContainers:
    - name: main-app
      image: main-app
      command: 'wait-for-db-to-start.sh'
    - name: api-checker    ## multiple init containers can exist
      image: busybox
      command: 'wait-for-another-api.sh'