## we first label the pod and then use the selector in replicaset to group the pods

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-webapp
  labels:
    app: App1
    function: Frontend
  annotations:
    description: "This is a simple webapp replicaset"
    buildVersion: 1.34
spec:
  replicas: 3
  selector:
    matchLabels:
      app: App1
  template:
    metadata:
      labels:
        app: App1
        function: Frontend
    spec:
      containers:
        - name: simple-webapp
          image: simple-webapp

## labels defined under template section are applied to the pod created by the replicaset
## labels at the top are for the replicaset object itself
## In order to connect replicaset to the pod we need to use selector field
