apiVersion: v1 
kind: Pod
metadata:
  name: simple-webapp
  labels:
    app: simple-webapp 
spec:
  containers:
  - name: simple-webapp
    image: simple-webapp
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /api/ready
        port: 8080
      initialDelaySeconds: 10 ## app takes 10 sec to warmup
      periodSeconds: 5  ## check every 5 sec
      failureThreshold: 3 ## after 3 failures mark it as not ready
    # readinessProbe:  ## other ways for readiness probe
    #   tcpSocket:
    #     port: 33
    # readinessProbe:
    #   exec:
    #     command:
    #     - cat
    #     - /app/is_ready

## by default if the application is not ready after 3 attempts. the probe will stop. If we want more attempts we can make use of failureThreshold