### kubectl create serviceaccount dashboard-sa
### kubectl get serviceaccount
### kubectl describe serviceaccount dashboard-sa
### kubectl describe secret dashboard-sa-token-xxxxx
## we cannot change the service account of a pod, we need to delete the pod and recreate it with the new service account
### we can change the service account for a deployment and the new pods will use the new service account


#with v1.24 there's a change in service account creation process - in earlier versions, when a service account was created, a secret was automatically created and associated with that service account.
# This secret contained the token that pods could use to authenticate as that service account. However, starting from v1.24, this automatic creation of secrets has been deprecated. Instead, Kubernetes now uses a different mechanism called Bound Service Account Tokens.
# These tokens are more secure and have a limited lifetime. They are automatically mounted into pods that use the service account, eliminating the need for manually created secrets.


## kubectl create serviceaccount dashboard-test-sa
## kubectl create token dashboard-test-sa


apiVersion: v1
kind: secret
type: kubernetes.io/service-account-token
metadata:
  name: dashboard-sa-token
  annotations:
    kubernetes.io/service-account.name: "dashboard-sa"

## the above secret is to create a non expiring token for a service account


